spring:
  application:
    name: team-service
  datasource:
    url: jdbc:h2:mem:teamdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${OKTA_CLIENT_ID}
            client-secret: ${OKTA_CLIENT_SECRET}
            scope: openid, profile, email
        provider:
          okta:
            issuer-uri: ${OKTA_ISSUER_URI}

server:
  port: 8083
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.geocell.team: DEBUG
    org.springframework: INFO
    org.springframework.security: INFO

okta:
  oauth2:
    issuer: ${OKTA_ISSUER_URI}
    audience: api://default
    client-id: ${OKTA_CLIENT_ID}

team-management:
  audit-logging:
    enabled: true
  sso:
    providers:
      - okta
      - google
      - azure
  roles:
    default-role: MEMBER
    available-roles:
      - ADMIN
      - MEMBER
      - VIEWER
      - EDITOR

saml:
  enabled: true
  providers:
    - name: azure-ad
      metadata-url: ${AZURE_AD_METADATA_URL}
    - name: google-workspace
      metadata-url: ${GOOGLE_WORKSPACE_METADATA_URL}

user-sync:
  enabled: true
  providers:
    - azure-ad
    - google-workspace
  sync-interval: 1h
