server:
  port: 8081
  servlet:
    context-path: /geocell

spring:
  application:
    name: survey-service
  
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:surveydb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com:
      geocell:
        survey: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
